language: python - "3.7"

before_install:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - "./miniconda.sh -b"
    - export PATH=$HOME/miniconda3/bin:$PATH
    - conda update --yes conda

install:
    - conda install --yes python=3.7
    - conda install --yes -c potassco clingo
    - conda install --yes sphinx
    - conda install --yes pyyaml
    - pip install --user travis-sphinx
    - export PATH=$HOME/.local/bin:$PATH

script:
    - travis-sphinx build

deploy:
    provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    local_dir: build
    on:
        branch: master

after_success:
    - travis-sphinx deploy

